/**
 * Starter templates (mirrored in config.lua Config.Documents.premadeTemplates).
 */
export const PREMADE_DOC_TEMPLATES = [
  {
    slug: 'employment_contract',
    name: 'Employment Contract',
    description: 'Hire agreement with role, pay, and start date',
    icon: 'contract',
    category: 'legal',
    requiresSignature: true,
    baseContent: '<p>This agreement is entered into between the employer and employee named below.</p>',
    fields: [
      { id: 'employee_name', label: 'Employee name', type: 'text', required: true },
      { id: 'role', label: 'Position', type: 'text', required: true },
      { id: 'salary', label: 'Salary ($)', type: 'number', required: false },
      { id: 'start_date', label: 'Start date', type: 'date', required: true },
    ],
  },
  {
    slug: 'traffic_citation',
    name: 'Traffic Citation',
    description: 'Moving violation notice for patrol citations',
    icon: 'citation',
    category: 'legal',
    requiresSignature: true,
    baseContent: '<p>You are cited for the violation described below. Sign to acknowledge receipt.</p>',
    fields: [
      { id: 'driver_name', label: 'Driver name', type: 'text', required: true },
      { id: 'plate', label: 'License plate', type: 'text', required: true },
      { id: 'vehicle', label: 'Vehicle description', type: 'text', required: false },
      { id: 'violation', label: 'Violation', type: 'textarea', required: true },
      { id: 'fine', label: 'Fine amount ($)', type: 'number', required: false },
      { id: 'citation_date', label: 'Date of citation', type: 'date', required: true },
    ],
  },
  {
    slug: 'medical_release',
    name: 'Medical Release',
    description: 'Authorize release of medical records',
    icon: 'medical',
    category: 'medical',
    requiresSignature: true,
    baseContent: '<p>I authorize the facility below to release my medical information to the party specified.</p>',
    fields: [
      { id: 'patient_name', label: 'Patient name', type: 'text', required: true },
      { id: 'facility', label: 'Medical facility', type: 'text', required: true },
      { id: 'recipient', label: 'Release to', type: 'text', required: true },
      { id: 'purpose', label: 'Purpose', type: 'textarea', required: true },
      { id: 'effective_date', label: 'Effective date', type: 'date', required: true },
    ],
  },
  {
    slug: 'nda',
    name: 'Non-Disclosure Agreement',
    description: 'Confidentiality between two parties',
    icon: 'legal',
    category: 'business',
    requiresSignature: true,
    baseContent: '<p>The parties agree to keep shared business information confidential for the term below.</p>',
    fields: [
      { id: 'party_a', label: 'Disclosing party', type: 'text', required: true },
      { id: 'party_b', label: 'Receiving party', type: 'text', required: true },
      { id: 'term_months', label: 'Term (months)', type: 'number', required: true },
      { id: 'effective_date', label: 'Effective date', type: 'date', required: true },
    ],
  },
  {
    slug: 'vehicle_sale',
    name: 'Vehicle Bill of Sale',
    description: 'Private vehicle transfer agreement',
    icon: 'business',
    category: 'business',
    requiresSignature: true,
    baseContent: '<p>The seller transfers ownership of the vehicle described below to the buyer.</p>',
    fields: [
      { id: 'seller', label: 'Seller name', type: 'text', required: true },
      { id: 'buyer', label: 'Buyer name', type: 'text', required: true },
      { id: 'vehicle', label: 'Vehicle (make/model)', type: 'text', required: true },
      { id: 'plate', label: 'Plate / VIN', type: 'text', required: true },
      { id: 'sale_price', label: 'Sale price ($)', type: 'number', required: true },
      { id: 'sale_date', label: 'Sale date', type: 'date', required: true },
    ],
  },
  {
    slug: 'rental_lease',
    name: 'Rental Agreement',
    description: 'Residential or commercial lease terms',
    icon: 'contract',
    category: 'legal',
    requiresSignature: true,
    baseContent: '<p>The landlord agrees to lease the property below to the tenant under these terms.</p>',
    fields: [
      { id: 'landlord', label: 'Landlord', type: 'text', required: true },
      { id: 'tenant', label: 'Tenant', type: 'text', required: true },
      { id: 'property', label: 'Property address', type: 'textarea', required: true },
      { id: 'rent', label: 'Monthly rent ($)', type: 'number', required: true },
      { id: 'deposit', label: 'Security deposit ($)', type: 'number', required: false },
      { id: 'lease_start', label: 'Lease start', type: 'date', required: true },
    ],
  },
  {
    slug: 'incident_report',
    name: 'Incident Report',
    description: 'Law enforcement or security incident log',
    icon: 'citation',
    category: 'general',
    requiresSignature: false,
    baseContent: '<p>Report of incident including location, parties, and narrative.</p>',
    fields: [
      { id: 'officer', label: 'Reporting officer', type: 'text', required: true },
      { id: 'location', label: 'Location', type: 'text', required: true },
      { id: 'involved', label: 'Parties involved', type: 'textarea', required: true },
      { id: 'narrative', label: 'Narrative', type: 'textarea', required: true },
      { id: 'incident_date', label: 'Date of incident', type: 'date', required: true },
    ],
  },
  {
    slug: 'witness_statement',
    name: 'Witness Statement',
    description: 'Sworn or informal witness account',
    icon: 'form',
    category: 'legal',
    requiresSignature: true,
    baseContent: '<p>I declare the following to be true to the best of my knowledge.</p>',
    fields: [
      { id: 'witness_name', label: 'Witness name', type: 'text', required: true },
      { id: 'case_ref', label: 'Case / reference #', type: 'text', required: false },
      { id: 'statement', label: 'Statement', type: 'textarea', required: true },
      { id: 'statement_date', label: 'Date', type: 'date', required: true },
    ],
  },
  {
    slug: 'warning_letter',
    name: 'Written Warning',
    description: 'HR disciplinary notice to employee',
    icon: 'document',
    category: 'business',
    requiresSignature: true,
    baseContent: '<p>This written warning documents the issue below and expected corrective action.</p>',
    fields: [
      { id: 'employee', label: 'Employee name', type: 'text', required: true },
      { id: 'department', label: 'Department', type: 'text', required: false },
      { id: 'issue', label: 'Issue / violation', type: 'textarea', required: true },
      { id: 'action', label: 'Required action', type: 'textarea', required: true },
      { id: 'warning_date', label: 'Date', type: 'date', required: true },
    ],
  },
  {
    slug: 'promissory_note',
    name: 'Promissory Note',
    description: 'Loan repayment agreement between parties',
    icon: 'legal',
    category: 'business',
    requiresSignature: true,
    baseContent: '<p>The borrower promises to repay the lender according to the terms below.</p>',
    fields: [
      { id: 'lender', label: 'Lender', type: 'text', required: true },
      { id: 'borrower', label: 'Borrower', type: 'text', required: true },
      { id: 'amount', label: 'Principal ($)', type: 'number', required: true },
      { id: 'due_date', label: 'Due date', type: 'date', required: true },
      { id: 'terms', label: 'Payment terms', type: 'textarea', required: false },
    ],
  },
  {
    slug: 'service_invoice',
    name: 'Service Invoice',
    description: 'Bill for services rendered',
    icon: 'business',
    category: 'business',
    requiresSignature: false,
    baseContent: '<p>Invoice for services listed below. Payment due by the date specified.</p>',
    fields: [
      { id: 'from', label: 'From (business)', type: 'text', required: true },
      { id: 'to', label: 'Bill to', type: 'text', required: true },
      { id: 'services', label: 'Services / items', type: 'textarea', required: true },
      { id: 'total', label: 'Total due ($)', type: 'number', required: true },
      { id: 'due_date', label: 'Due date', type: 'date', required: true },
    ],
  },
  {
    slug: 'treatment_consent',
    name: 'Treatment Consent',
    description: 'Consent for medical procedure',
    icon: 'medical',
    category: 'medical',
    requiresSignature: true,
    baseContent: '<p>I consent to the treatment described below and acknowledge the risks explained to me.</p>',
    fields: [
      { id: 'patient', label: 'Patient name', type: 'text', required: true },
      { id: 'procedure', label: 'Procedure', type: 'text', required: true },
      { id: 'physician', label: 'Attending physician', type: 'text', required: true },
      { id: 'consent_date', label: 'Date', type: 'date', required: true },
    ],
  },
]

export function mapPremadeForUi(t) {
  return {
    id: `premade:${t.slug}`,
    name: t.name,
    description: t.description || '',
    icon: t.icon || 'document',
    category: t.category || 'general',
    fields: t.fields || [],
    requiresSignature: !!t.requiresSignature,
    baseContent: t.baseContent || '',
    isPremade: true,
    timeAgo: 'Starter',
  }
}
